# Site settings
author: Micah White
title: A New Path
header-img: img/home-bg.png
email: micahjwhite@gmail.com
copyright_name: Micah White
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code and Think Differently at Flatiron School
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: micahjwhite
github_username:  micahjwhite

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
